//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CORE.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ParkingService
    {
        public int Id { get; set; }
        public int IdRate { get; set; }
        public int IdVehicle { get; set; }
        public System.DateTime DateTimeEntry { get; set; }
        public Nullable<System.DateTime> DateTimeExit { get; set; }
        public Nullable<decimal> ServicePrice { get; set; }
        public int Estate { get; set; }
    
        public virtual Rates Rates { get; set; }
        public virtual Vehicle Vehicle { get; set; }
    }
}
